### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by MADEiN83** [bcoe/conventional-release-labels#28]
I'm having this issue:

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/9880560/168026976-39fe80ff-2a8d-46c1-80bd-ef09ef12f870.png">

with this basic workflow:

```
on:
  pull_request:
    types: [opened, edited]

name: conventional-release-labels

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
```
