### ISSUE TITLE
[Bug] "unexpected token ' ' at 1:5, valid tokens [(, !, :]"

### ISSUE THREAD

**Issue by vincentchalamon** [bcoe/conventional-release-labels#30]
Using the following configuration, a commit named `chore: test PR labeler` and a PR title `Test PR labeler`:
```yaml
name: Pull Request Labeler
on:
  pull_request_target:
    types: [ opened ]
jobs:
  label:
    name: Add Pull Request labels
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          type_labels: '{"feat": "enhancement", "fix": "bug", "docs": "documentation", "chore": "chore"}'
          ignored_types: '[]'
          ignore_label: 'ignore-for-release'
```

I get the following error:
> unexpected token ' ' at 1:5, valid tokens [(, !, :]

The job don't fail (false-positive) and the `chore` label is not set on the PR.
