### ISSUE TITLE
How To Add Custom type_labels?

### ISSUE THREAD

**Issue by mehdihadeli** [bcoe/conventional-release-labels#37]
Hi @bcoe,
How can I define some extra `type_labels` for conventional commits instead of default ones?

**Comment by gardar** [comment]
Just add them as string containing a json dict under the job, like so:

```yaml
- uses: bcoe/conventional-release-labels@v1
   with:
     type_labels: '{"feat": "feature", "fix": "fix", "breaking": "breaking"}'
```
